name = "Alternate Current"
filename = "alternate-current-mc1.17-0.3.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/r0v8vy1s/versions/mc1.17-0.3.0/alternate-current-mc1.17-0.3.0.jar"
hash-format = "sha512"
hash = "81a6ff95483a7a0c51ddc816b4ffa46db99addc53d6ccf6192bdaa88a4b04950f849280dbb04ff629fc102fe56780f6d8308f267cfa0a40f72c35c8975bb3efc"

[update]
[update.modrinth]
mod-id = "r0v8vy1s"
version = "1ebDeupo"
