name = "Fading"
filename = "fading-1.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/meiwLTDg/versions/1.3.0/fading-1.3.0.jar"
hash-format = "sha512"
hash = "43f8633ff6d8eb89d75654b8e6a3ca82ab231c3138120a8dcd60c0f36f128a8cb82707993e4628e4e93570313fbcd0faf483095afdccb13084057c72edfd9cbe"

[update]
[update.modrinth]
mod-id = "meiwLTDg"
version = "5Xnop4Mw"
