name = "Happiness (is a) Warm Gun"
filename = "HWGMod-1.17-1.0.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/207/HWGMod-1.17-1.0.17.jar"
hash-format = "murmur2"
hash = "1092480223"

[update]
[update.curseforge]
file-id = 3455207
project-id = 448106
release-channel = "beta"
