name = "Neutrino"
filename = "Neutrino-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3459/750/Neutrino-0.2.0.jar"
hash-format = "murmur2"
hash = "2004451036"

[update]
[update.curseforge]
file-id = 3459750
project-id = 522461
release-channel = "beta"
