name = "WTHIT"
filename = "wthit-fabric-3.9.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com//data/6AQIaxuO/versions/fabric-3.9.0/wthit-fabric-3.9.0.jar"
hash-format = "sha512"
hash = "d2a7a57469175f0d9554d4fd49ecf098d7367916e3b66a6c4c2fa366633b5ff00f4704c6e248f60ebfcfb4552bbf3c68e2bee0757bcd10266ab549276c936205"

[update]
[update.modrinth]
mod-id = "6AQIaxuO"
version = "a3q7LxU1"
